MASK_MAIL_ADDRESS: "phosawas@siamsaison.com"
MASK_MAIL_PASSWORD: "iwnumpprvqbxixra"
MAIL_USER_NAME: "admin@siamsaison.com"
MAIL_PASSWORD: "nga5Jortres"
MAIL_USER_NAME_PDPA: "admin@siamsaison.com"
MAIL_PASSWORD_PDPA: "nga5Jortres"
mask_mobile_number: "0805752869"
JV_THAIBULK_API_KEY: qm1k14oSWgqqemLOeMZnMqX1LemzKC
JV_THAIBULK_API_SECRET: 67aIbuDEQn_vT2P03-oZOXQ7RnTmKK