MASK_MAIL_ADDRESS: "phosawas.p@gmail.com"
MASK_MAIL_PASSWORD: "iwnumpprvqbxixra"
MAIL_USER_NAME: "phosawas.p@gmail.com"
MAIL_PASSWORD: "iwnumpprvqbxixra"
MAIL_USER_NAME_PDPA: "phosawas.p@gmail.com"
MAIL_PASSWORD_PDPA: "iwnumpprvqbxixra"
mask_mobile_number: "0805752869"